import {
  Activity,
  ALargeSmall,
  Archive,
  ArrowLeft,
  ArrowRightLeft,
  ArrowUp,
  Bell,
  Bookmark,
  BookmarkPlus,
  Bot,
  Brain,
  BrainCircuit,
  Bug,
  Camera,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleHelp,
  CircleStop,
  Clipboard,
  Copy,
  Cpu,
  Crosshair,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  Folder,
  FolderOpen,
  GitCompare,
  GitMerge,
  Globe,
  Globe2,
  Grid2X2,
  GripVertical,
  HardDrive,
  History,
  Images,
  LayoutDashboard,
  Link,
  ListFilter,
  ListTodo,
  Loader2,
  Lock,
  LogOut,
  Maximize2,
  MemoryStick,
  MessageSquare,
  MessageSquareX,
  Mic,
  Minimize2,
  Minus,
  Monitor,
  MoreHorizontal,
  MousePointer2,
  MoveHorizontal,
  Network,
  Palette,
  PanelRight,
  PanelsTopLeft,
  PanelTopOpen,
  Paperclip,
  Pause,
  Pencil,
  Pin,
  PinOff,
  Play,
  Plus,
  Printer,
  Radio,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Route,
  Save,
  Star,
  Search,
  Send,
  ServerCog,
  Settings2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Shrink,
  Smartphone,
  Sparkles,
  Square,
  Tablet,
  Terminal,
  Trash2,
  TriangleAlert,
  Unplug,
  Undo2,
  Upload,
  UserCheck,
  Users,
  Video,
  Wrench,
  X,
  Zap,
  type LucideIcon
} from "../ui-theme/app-icons.js";

export type HelpBadge = "ADMIN" | "CONDITIONAL" | "INFORMATIONAL";

export interface HelpEntry {
  id: string;
  label: string;
  icon: LucideIcon;
  location: string;
  description: string;
  badges?: HelpBadge[];
}

export interface HelpSection {
  id: string;
  title: string;
  summary: string;
  entries: HelpEntry[];
}

const entry = (
  id: string,
  label: string,
  icon: LucideIcon,
  location: string,
  description: string,
  badges?: HelpBadge[]
): HelpEntry => ({ id, label, icon, location, description, badges });

export const helpSections: HelpSection[] = [
  {
    id: "getting-started",
    title: "Getting started",
    summary: "The Space mental model and the controls that move you between the workspace and this guide.",
    entries: [
      entry("help", "Help", CircleHelp, "Fixed room controls", "Opens this complete Space guide at the dedicated /help address."),
      entry("back-to-space", "Back to Space", ArrowLeft, "Help header", "Returns to the room you were using without signing out of Space."),
      entry("space-workspace", "Space workspace", LayoutDashboard, "Application header", "Represents the room control plane that contains docks, panes, agents, and browser sessions.", ["INFORMATIONAL"]),
      entry("room-concept", "Rooms", PanelRight, "Workspace", "Rooms are persistent work areas that group related panes, tasks, media, clipboard history, and supervision."),
      entry("pane-concept", "Panes", Grid2X2, "Room board", "Panes are the individual chat, CLI, browser, review, code, swarm, or design work surfaces inside a room."),
      entry("command-target", "Active command target", Crosshair, "Pane selection", "Shows which non-CLI pane receives global commands, clipboard insertion, and other targeted actions."),
      entry("agent-number", "Agent badge", Bot, "Pane header", "Identifies the pane type and its stable Agent number within the current room.", ["INFORMATIONAL"]),
      entry("sign-out", "Sign out", LogOut, "Fixed room controls", "Ends the authenticated Space session and returns to the operator login screen.")
    ]
  },
  {
    id: "rooms-and-navigation",
    title: "Rooms and navigation",
    summary: "Create, organize, rename, switch, focus, and remove persistent rooms.",
    entries: [
      entry("create-room", "New room", Plus, "Rooms dock", "Creates and selects an empty, automatically named room so panes can be added from the room composer."),
      entry("room-pane-composer", "Room pane composer", Grid2X2, "Rooms dock footer", "Adds exactly the selected mix of available non-root CLI runtimes and Chat panes to the room marked as the pane target."),
      entry("open-room", "Open room", Eye, "Rooms dock", "Loads the selected room, its panes, recent turns, events, and room-level state."),
      entry("reorder-room", "Reorder room", GripVertical, "Rooms dock", "Drag this handle to change the persistent order of rooms in the dock."),
      entry("delete-room", "Delete room", Trash2, "Rooms dock", "Permanently removes the room after the server accepts the delete request."),
      entry("rename-room", "Rename room", Pencil, "Room title", "Turns the current room name into an editable field."),
      entry("save-room-name", "Save room name", Save, "Room title editor", "Saves a non-empty room name and updates the Rooms dock."),
      entry("cancel-room-name", "Cancel room rename", Undo2, "Room title editor", "Discards the room-name draft and restores the current saved name."),
      entry("previous-room", "Previous room", ChevronLeft, "Room title", "Moves to the previous room in the saved room order when one exists."),
      entry("next-room", "Next room", ChevronRight, "Room title", "Moves to the next room in the saved room order when one exists."),
      entry("maximize-room", "Maximize room", Maximize2, "Fixed room controls", "Hides the top shell and side surface so the room board gets the available viewport."),
      entry("restore-room", "Restore room", Minimize2, "Focused room", "Leaves room focus mode and restores the normal header and side-surface layout.")
    ]
  },
  {
    id: "room-toolbar",
    title: "Room toolbar",
    summary: "Global room actions, pane creation, links, capture tools, and privileged operations.",
    entries: [
      entry("surface-rooms", "Rooms", PanelRight, "Room toolbar", "Shows or hides the persistent room list and its room creation action."),
      entry("surface-room-agent", "Room Agent", Bot, "Room toolbar", "Opens the persistent supervisor that can coordinate work across the current room."),
      entry("surface-media", "Media dock", Images, "Room toolbar", "Opens room images, recordings, uploaded files, and browser evidence artifacts."),
      entry("surface-streaming", "Streaming dock", Radio, "Room toolbar", "Opens ADMIN controls for official YouTube, Twitch, and TikTok connections plus the global Space statistics overlay.", ["ADMIN", "CONDITIONAL"]),
      entry("surface-agent-files", "Agent Files", FolderOpen, "Room toolbar", "Opens room-scoped final deliverables published by agents, with safe preview, download, and permanent deletion controls."),
      entry("surface-clipboard", "Clipboard", Clipboard, "Room toolbar", "Opens private Space-wide clipboard history, notes, search, and insertion controls."),
      entry("surface-tasks", "Tasks", ListTodo, "Room toolbar", "Opens private Space-wide task declarations with a status lifecycle, search, and drag-to-CLI auto-start."),
      entry("surface-agent-sessions", "Agent Session History", History, "Room toolbar", "Lists recent Codex threads and CLI sessions across providers with search, resume, rename, and archive controls."),
      entry("surface-links", "Links", Link, "Room toolbar", "Opens your synchronized personal link library with search, add, edit, delete, and Quick Link controls."),
      entry("surface-settings", "Settings dock", Settings2, "Room toolbar", "Opens provider, Telegram, voice, CLI preview, agent model, reasoning, and tool settings."),
      entry("surface-health", "Health dock", Activity, "Room toolbar", "Shows runtime, worker, provider, storage, MCP, and request health at a glance."),
      entry("memory-workspace", "Open memory workspace", Network, "Room toolbar", "Opens the full memory graph workspace for search, inspection, review, and maintenance visibility."),
      entry("quick-links", "Quick Links", Star, "Room toolbar", "Opens only the links you starred, with pagination and a Manage Links shortcut."),
      entry("pane-layout", "Pane layout", PanelsTopLeft, "Room toolbar", "Applies Automatic or one-to-four-column room presets to visible panes without creating, closing, or restarting panes."),
      entry("room-theme", "Room theme", Palette, "Room toolbar", "Opens the saved room-theme choices and applies the selected visual theme."),
      entry("cli-floats", "Hide or show CLI floats", EyeOff, "Room toolbar", "Hides or restores the END, model, and Send or Stop overlays in every CLI pane, and remembers the choice in this browser."),
      entry("sensitive-data", "Hide or show sensitive data", EyeOff, "Room toolbar", "Blurs private IPs, emails, and internal domains (including example.invalid) across the whole Space UI, and remembers the choice in this browser."),
      entry("font-down", "Workspace text size", ALargeSmall, "Room toolbar", "Opens the 10–20 px wheel picker and applies the selected size immediately to every chat and CLI pane."),
      entry("add-chat", "Add chat pane", MessageSquare, "Room toolbar", "Adds a Codex chat pane to the room when fewer than 16 panes are open."),
      entry("add-cli", "Add CLI pane", Terminal, "Room toolbar", "Opens the shared non-root CLI launcher with OpenCode (default free DeepSeek V4 Flash), Codex, Claude Code, Gemini, Autohand Code, Qwen Code, Kimi Code, Grok Build, DeepSeek, Cursor, and GitHub Copilot choices."),
      entry("add-opencode", "Add OpenCode CLI", Terminal, "Add CLI pane selector", "Adds a CLI pane configured to run the available OpenCode runtime with the free DeepSeek V4 Flash default model.", ["CONDITIONAL"]),
      entry("add-codex", "Add Codex CLI", Terminal, "Add CLI pane selector", "Adds a standard Codex terminal through the existing default CLI N pane flow."),
      entry("add-claude", "Add Claude Code CLI", Terminal, "Add CLI pane selector", "Adds a CLI pane configured to run the available Claude Code runtime.", ["CONDITIONAL"]),
      entry("add-gemini", "Add Gemini CLI", Terminal, "Add CLI pane selector", "Adds a CLI pane configured to run the authenticated Gemini CLI runtime.", ["CONDITIONAL"]),
      entry("add-autohand", "Add Autohand Code CLI", Terminal, "Add CLI pane selector", "Opens the controlled Autohand account and OpenRouter setup flow, then adds its CLI pane when authentication is ready.", ["CONDITIONAL"]),
      entry("add-qwen", "Add Qwen Code CLI", Terminal, "Add CLI pane selector", "Adds a CLI pane configured to use the authenticated Alibaba Coding Plan International runtime.", ["CONDITIONAL"]),
      entry("add-kimi", "Add Kimi Code CLI", Terminal, "Add CLI pane selector", "Adds a CLI pane configured to use the authenticated Kimi Code subscription runtime.", ["CONDITIONAL"]),
      entry("add-grok", "Add Grok Build CLI", Terminal, "Add CLI pane selector", "Adds a CLI pane configured to use the authenticated xAI Grok Build account runtime.", ["CONDITIONAL"]),
      entry("add-deepseek", "Add DeepSeek CLI", Terminal, "Add CLI pane selector", "Adds a text-chat CLI pane that resolves a provider-advertised model after protected API-key setup.", ["CONDITIONAL"]),
      entry("add-cursor", "Add Cursor CLI", Terminal, "Add CLI pane selector", "Adds a CLI pane that uses the authenticated Cursor account and its native provider model catalog.", ["CONDITIONAL"]),
      entry("add-copilot", "Add GitHub Copilot CLI", Terminal, "Add CLI pane selector", "Adds a CLI pane that uses the authenticated GitHub Copilot account and its native provider model catalog.", ["CONDITIONAL"]),
      entry("add-root", "Add CLI ROOT", ShieldCheck, "Room toolbar", "Adds a protected root shell pane rooted at /etc for privileged administration.", ["ADMIN", "CONDITIONAL"]),
      entry("restart-server", "Server restart", ServerCog, "Room toolbar", "Opens a confirmation that restarts Space web, API, and worker services while protecting pane hosts.", ["ADMIN", "CONDITIONAL"]),
      entry("add-browser", "Add browser pane", Eye, "Room toolbar", "Adds a managed Chrome browser pane to the current room."),
      entry("add-review", "Add review pane", GitCompare, "Room toolbar", "Adds a review-mode pane for workflow state and review-oriented room work."),
      entry("reload-window", "Reload window", RefreshCw, "Room toolbar", "Refreshes Space data for the current room without using a browser hard reload."),
      entry("clip-tool", "Clip Tool", Camera, "Room toolbar", "Captures the desktop screen, or lets mobile and tablet users choose a screenshot or photo, then attaches it to the active chat or CLI pane."),
      entry("print-window", "Print window", Printer, "Room toolbar", "Opens the browser print dialog for the currently visible Space view."),
      entry("more-room-actions", "More room actions", MoreHorizontal, "Fixed room controls", "Opens the action manager for hidden, reordered, and overflowed room toolbar controls."),
      entry("room-toolbar-maximize", "Maximize or restore room", Maximize2, "Fixed room controls", "Toggles the room between the normal shell and the distraction-reduced focused layout.")
    ]
  },
  {
    id: "system-metrics",
    title: "System metrics",
    summary: "Live capacity badges and guarded maintenance actions in the room header.",
    entries: [
      entry("metric-all", "ALL account capacity", Users, "System metric strip", "Shows the remaining percentage across every enabled Codex account and opens account details."),
      entry("metric-cli", "CLI sessions", Terminal, "System metric strip", "Shows active Space CLI sessions and opens details for attached, detached, and cleanup-eligible sessions."),
      entry("metric-cli-clean", "Clean detached CLI sessions", Trash2, "CLI metric confirmation", "Reaps only eligible Space-managed sessions that have remained detached long enough.", ["ADMIN", "CONDITIONAL"]),
      entry("metric-ram", "RAM usage", MemoryStick, "System metric strip", "Shows host memory usage and opens available memory, page cache, pressure, and top-process details."),
      entry("metric-memory-reclaim", "Reclaim safe memory", RefreshCw, "RAM metric confirmation", "Rechecks pressure, cleans eligible detached CLIs, and drops page cache only when safe.", ["ADMIN", "CONDITIONAL"]),
      entry("metric-cpu", "CPU usage", Cpu, "System metric strip", "Displays current host CPU utilization and available core count.", ["INFORMATIONAL"]),
      entry("metric-swap", "SWP usage", HardDrive, "System metric strip", "Displays current swap usage and the used-versus-total amount.", ["INFORMATIONAL"]),
      entry("metric-provider", "Provider route", Route, "System metric strip", "Shows the active provider route and offers an authorized quick switch between healthy targets.", ["ADMIN", "CONDITIONAL"])
    ]
  },
  {
    id: "pane-controls",
    title: "Pane controls",
    summary: "Controls shared by pane headers, including layout, targeting, imports, and task lifecycle actions.",
    entries: [
      entry("pane-mode", "Pane mode badge", Grid2X2, "Pane header", "Identifies whether the pane is Chat, CLI, Browser, Review, Code, Swarm, or Design.", ["INFORMATIONAL"]),
      entry("edit-pane-title", "Edit pane title", Pencil, "Pane header", "Opens the pane-title editor for a manual name change."),
      entry("save-pane-title", "Save pane title", Save, "Pane title editor", "Persists the edited pane name when the value is valid."),
      entry("cancel-pane-title", "Cancel pane title", Undo2, "Pane title editor", "Closes title editing and restores the current saved title."),
      entry("generate-pane-title", "Generate pane title", Sparkles, "CLI pane header", "Uses AI to derive a short title from the current non-root CLI task.", ["CONDITIONAL"]),
      entry("import-pane-files", "Attach or upload files", Paperclip, "Pane header", "Attaches files to chat, uploads files to CLI, or imports files into other pane types."),
      entry("pane-plan", "Enable Plan mode", PanelRight, "Chat or CLI pane header", "Switches a supported agent or CLI session into planning mode before execution.", ["CONDITIONAL"]),
      entry("pane-resume", "Resume task", Send, "Chat pane header", "Requests continuation of the current Codex chat task."),
      entry("pane-stop", "Stop task", CircleStop, "Pane header", "Interrupts the active chat, CLI, or root-shell task without closing the pane."),
      entry("pane-memory", "Save task to memory", Database, "Chat pane header", "Saves the current task context into Space memory for later discovery."),
      entry("pane-copy", "Copy CLI contents", Copy, "CLI pane header", "Copies the visible CLI terminal buffer to the system clipboard."),
      entry("pane-reconnect", "Reconnect CLI", RefreshCw, "CLI pane header", "Reconnects the pane to its protected live terminal session."),
      entry("pane-move", "Move pane", ArrowRightLeft, "Pane header", "Moves the pane and its bound state to another existing room."),
      entry("pane-target", "Use as command target", Crosshair, "Non-CLI pane header", "Makes this pane the recipient of targeted global actions and clipboard insertion."),
      entry("pane-split", "Add pane", PanelTopOpen, "Pane header", "Creates another pane of the same type using this pane as the horizontal split parent."),
      entry("pane-grow", "Grow pane width", MoveHorizontal, "Pane header", "Increases the pane column span when the desktop grid has available space.", ["CONDITIONAL"]),
      entry("pane-reset", "Reset pane width", Shrink, "Pane header", "Returns a widened pane to its normal single-column span.", ["CONDITIONAL"]),
      entry("pane-more", "More pane actions", MoreHorizontal, "Fixed pane controls", "Opens the pane action manager, including hidden and overflowed controls."),
      entry("pane-maximize", "Maximize pane", Maximize2, "Fixed pane controls", "Expands one pane to occupy the room board while keeping its session active."),
      entry("pane-restore", "Restore pane size", Minimize2, "Fixed pane controls", "Returns a maximized or mobile-focused pane to the room grid."),
      entry("pane-minimize", "Minimize pane", Minus, "Desktop and tablet pane controls", "Hides any pane while keeping its session mounted; the state persists across refreshes and room switches."),
      entry("pane-title-restore", "Restore minimized pane", PanelTopOpen, "Minimized panes bar", "Restores a minimized pane by its current full title and returns keyboard focus to that pane."),
      entry("pane-restore-all", "Restore all panes", Grid2X2, "Minimized panes bar", "Restores every minimized pane to the normal grid and clears pane maximization."),
      entry("pane-close", "Close pane", X, "Fixed pane controls", "Closes the pane through Space and removes it from the room."),
      entry("pane-end", "END completion chip", CheckCircle2, "Pane card", "Marks a newly completed CLI turn until the pane is acknowledged.", ["INFORMATIONAL", "CONDITIONAL"])
    ]
  },
  {
    id: "chat-panes",
    title: "Chat panes",
    summary: "Codex task history, context, permissions, models, tools, voice, and message controls.",
    entries: [
      entry("chat-new-task", "New task", Plus, "Chat header", "Starts a fresh Codex task in the current chat pane."),
      entry("chat-history", "Task history", Folder, "Chat header", "Opens recent Codex threads for the current workspace and resumes the selected task."),
      entry("chat-current-task", "Current task", Check, "Task history", "Marks the history entry currently attached to the chat pane.", ["INFORMATIONAL"]),
      entry("chat-more", "More task actions", MoreHorizontal, "Chat header", "Opens secondary task actions such as refresh and new task."),
      entry("chat-refresh", "Refresh task", RefreshCw, "Task action menu", "Reloads the current chat thread and its latest state."),
      entry("chat-model", "Model and reasoning", Brain, "Chat composer", "Selects the model/provider combination and reasoning effort for future turns."),
      entry("chat-advanced", "Advanced model controls", Zap, "Model menu", "Reveals reasoning effort and web-search toggles for the selected model."),
      entry("chat-search", "Web Search", Globe, "Model menu", "Enables the required browser search tools when a browser pane makes them available.", ["CONDITIONAL"]),
      entry("chat-permissions", "Agent permissions", Shield, "Chat composer", "Chooses ask-for-approval, approve-for-me, or confirmed full-access behavior for the next turn."),
      entry("chat-add-context", "Add context", Plus, "Chat composer", "Opens files, folders, goals, Plan mode, memory, skills, MCP, and browser tool controls."),
      entry("chat-files", "Files", File, "Add context menu", "Attaches one or more files as context for the next chat turn."),
      entry("chat-folder", "Folder", FolderOpen, "Add context menu", "Adds a selected folder as task context when supported."),
      entry("chat-goal", "Goal", Sparkles, "Add context menu", "Creates, updates, or clears a durable task objective for the chat."),
      entry("chat-plan-mode", "Plan mode", Brain, "Add context menu", "Toggles the chat between normal collaboration and plan-only collaboration."),
      entry("chat-tools", "Tools", Wrench, "Add context menu", "Enables available memory, skill, MCP, and browser tools for the next turn."),
      entry("chat-attachments", "Attachments", Paperclip, "Chat composer", "Shows staged attachments and lets you remove one item or clear the set."),
      entry("chat-voice", "Voice input", Mic, "Chat composer", "Starts or stops OpenAI live transcription, then submits the finished Chat prompt immediately."),
      entry("chat-send", "Send chat prompt", ArrowUp, "Chat composer", "Submits the prompt, selected context, model, permissions, tools, and goal to Codex."),
      entry("chat-stop", "Stop chat task", CircleStop, "Chat composer", "Interrupts the running Codex turn when the session supports interruption."),
      entry("chat-retry", "Retry failed action", RotateCw, "Chat transcript", "Retries a recoverable failed Codex response or tool action.", ["CONDITIONAL"]),
      entry("chat-tool-call", "Tool call", Wrench, "Chat transcript", "Expands the details and result of a tool used during the task.", ["INFORMATIONAL"])
    ]
  },
  {
    id: "cli-panes",
    title: "CLI panes",
    summary: "Protected live terminal sessions, model control, task history, uploads, clipboard routing, and turn control.",
    entries: [
      entry("cli-live", "Live CLI terminal", Terminal, "CLI pane", "Displays and controls the protected live shell or agent runtime attached to the pane."),
      entry("cli-voice", "Voice input", Mic, "CLI floating controls", "Starts or stops OpenAI live transcription, then sends the finished transcript to the attached CLI."),
      entry("cli-model", "CLI model and reasoning", BrainCircuit, "CLI floating controls", "Changes the active Codex model and reasoning effort without replacing the terminal session.", ["CONDITIONAL"]),
      entry("cli-resume", "Resume CLI task", History, "CLI pane header", "Searches shared Space CLI task history and continues the selected task in the pane's existing runtime.", ["CONDITIONAL"]),
      entry("cli-plan", "CLI Plan mode", PanelRight, "CLI pane header", "Sends the runtime-specific control needed to enter planning mode."),
      entry("cli-memory", "Save CLI task to memory", Database, "CLI pane header", "Requests a room-scoped memory save using the current CLI task context."),
      entry("cli-copy", "Copy terminal buffer", Copy, "CLI pane header", "Copies the current terminal contents without interrupting the running process."),
      entry("cli-upload", "Upload files to CLI", Paperclip, "CLI pane header", "Uploads files and safely inserts their server paths into the active terminal."),
      entry("cli-drop", "Drop files or photos", Upload, "CLI pane body", "Accepts drag-and-drop uploads and prepares them for the live CLI session."),
      entry("cli-paste", "Paste text or image", Clipboard, "CLI pane body", "Routes text to terminal input and images through Space upload storage before insertion."),
      entry("cli-preview", "Open image preview", Images, "CLI upload strip", "Opens a full-size preview without echoing the server upload path into the transcript."),
      entry("cli-dismiss-preview", "Dismiss image preview", X, "CLI upload strip", "Removes one preview or clears the transient image preview strip."),
      entry("cli-send", "Send prompt", ArrowUp, "CLI floating controls", "Sends the prepared prompt to an idle Codex CLI turn."),
      entry("cli-stop", "Stop Codex", Square, "CLI floating controls", "Sends the stop control to the currently running Codex CLI turn."),
      entry("cli-loading", "CLI loading", Loader2, "CLI pane", "Indicates that runtimes or session state are still being attached.", ["INFORMATIONAL"]),
      entry("cli-close-debug", "Close CLI debug panel", X, "CLI debug panel", "Dismisses the visible clipboard diagnostic panel without changing the session.", ["CONDITIONAL"])
    ]
  },
  {
    id: "browser-panes",
    title: "Browser panes",
    summary: "Managed Chrome tabs, control handoff, responsive viewports, evidence capture, recording, and debugging.",
    entries: [
      entry("browser-tab", "Browser tab", Globe2, "Browser pane", "Selects an existing managed Chrome page and displays its current title and URL."),
      entry("browser-close-tab", "Close browser tab", X, "Browser tab strip", "Closes the selected managed browser page."),
      entry("browser-new-tab", "New browser tab", Plus, "Browser tab strip", "Creates another page inside the current managed browser session."),
      entry("browser-navigate", "Navigate browser", Send, "Browser address bar", "Navigates the active managed page to the entered URL."),
      entry("browser-pc", "PC view", Monitor, "Browser toolbar", "Sets the managed page to the desktop viewport profile."),
      entry("browser-tablet", "Tablet view", Tablet, "Browser toolbar", "Sets the managed page to the tablet viewport profile."),
      entry("browser-mobile", "Mobile view", Smartphone, "Browser toolbar", "Sets the managed page to the mobile viewport profile."),
      entry("browser-bookmarks", "Browser bookmarks", Bookmark, "Browser toolbar", "Opens managed bookmarks for the active browser session."),
      entry("browser-bookmark-save", "Save current browser page", BookmarkPlus, "Bookmark menu", "Saves the active page to the Space-managed bookmark collection."),
      entry("browser-bookmark-import", "Import browser bookmarks", Upload, "Bookmark menu", "Imports supported bookmarks from a Chrome JSON export."),
      entry("browser-bookmark-export", "Export browser bookmarks", Download, "Bookmark menu", "Downloads the managed bookmark collection as JSON."),
      entry("browser-refresh", "Refresh browser frame", RefreshCw, "Browser toolbar", "Requests a fresh rendered frame from the active browser session."),
      entry("browser-reconnect", "Reconnect browser", RotateCw, "Browser toolbar", "Reattaches the pane to its managed browser session after a disconnect."),
      entry("browser-handoff", "Join browser session", UserCheck, "Browser toolbar", "Acquires an operator control lease for click, touch, scroll, and text input."),
      entry("browser-release", "Release browser control", UserCheck, "Browser toolbar", "Releases the operator lease and returns control to mediated automation.", ["CONDITIONAL"]),
      entry("browser-screenshot", "Capture browser screenshot", Camera, "Browser toolbar", "Captures the current managed page as a Space evidence artifact."),
      entry("browser-record", "Record browser session", Video, "Browser toolbar", "Opens duration controls for a resumable browser recording."),
      entry("browser-debug", "Open browser debugger", Bug, "Browser toolbar", "Opens console, network, frame history, recordings, and evidence diagnostics."),
      entry("browser-focus", "Expand browser view", Maximize2, "Browser toolbar", "Expands the managed page view within the browser pane."),
      entry("browser-unfocus", "Exit browser focus mode", Minimize2, "Browser toolbar", "Returns the browser pane from its expanded page view."),
      entry("browser-stop", "Stop browser session", CircleStop, "Browser toolbar", "Stops the managed browser session and clears its active control lease."),
      entry("browser-type", "Type into browser", Send, "Browser handoff controls", "Types text into the focused page element while operator control is active.", ["CONDITIONAL"]),
      entry("browser-pointer", "Click browser frame", MousePointer2, "Browser handoff view", "Sends the translated pointer location to the managed page.", ["CONDITIONAL"]),
      entry("browser-record-start", "Start browser recording", Play, "Recording controls", "Starts recording for the selected duration and preserves resumable progress."),
      entry("browser-record-stop", "Stop and save recording", Square, "Recording controls", "Stops the active recording and finalizes the captured video artifact."),
      entry("browser-record-cancel", "Cancel browser recording", Trash2, "Recording controls", "Cancels the active recording and discards its unfinished capture."),
      entry("browser-frame-previous", "Previous browser frame", ChevronLeft, "Browser debugger", "Moves backward through the captured browser frame timeline."),
      entry("browser-frame-next", "Next browser frame", ChevronRight, "Browser debugger", "Moves forward through the captured browser frame timeline."),
      entry("browser-artifact-pin", "Pin browser artifact", Pin, "Browser debugger", "Pins an evidence artifact so it remains prominent for later review."),
      entry("browser-artifact-unpin", "Unpin browser artifact", PinOff, "Browser debugger", "Removes the pinned state from a browser evidence artifact.")
    ]
  },
  {
    id: "docks-and-settings",
    title: "Docks and settings",
    summary: "Room supervision, media, clipboard, integrations, voice, provider settings, and health panels.",
    entries: [
      entry("agent-supervisor", "Persistent room supervisor", Bot, "Room Agent dock", "Coordinates a room mission, reports progress and quality, and follows up across active panes."),
      entry("agent-clear", "Clear Room Agent history", MessageSquareX, "Room Agent dock", "Clears visible supervisor conversation while preserving the durable goal and evidence."),
      entry("agent-pause", "Pause Room Agent", Pause, "Room Agent dock", "Pauses an active supervised mission when the session exposes pause capability.", ["CONDITIONAL"]),
      entry("agent-resume", "Resume Room Agent", Play, "Room Agent dock", "Resumes a paused supervised mission when recovery is available.", ["CONDITIONAL"]),
      entry("agent-stop", "Stop Room Agent", CircleStop, "Room Agent dock", "Stops the current supervised mission without deleting its report."),
      entry("agent-send", "Send to Room Agent", Send, "Room Agent dock", "Queues a room-level assignment or follow-up for the persistent supervisor."),
      entry("media-open", "Open media", Images, "Media dock", "Opens an image, video, or file artifact from the current room."),
      entry("media-fullscreen", "Maximize media", Maximize2, "Media dock", "Switches the media list into a full-screen gallery layout."),
      entry("media-restore", "Exit media fullscreen", Minimize2, "Media dock", "Returns the media gallery to the side-dock layout."),
      entry("media-refresh", "Refresh media", RefreshCw, "Media dock", "Reloads the latest media artifacts for the active room."),
      entry("media-clear", "Clear all media", Trash2, "Media dock", "Permanently deletes all eligible media artifacts in the room."),
      entry("streaming-session", "Streaming overlay activation", Radio, "Streaming dock", "Shows or hides the overlay only in the current browser tab; the activation choice is not saved globally.", ["ADMIN"]),
      entry("streaming-providers", "Streaming providers", Radio, "Streaming dock", "Shows secure server readiness, official OAuth connections, connected accounts, verification, removal, and authorization disconnect controls.", ["ADMIN", "CONDITIONAL"]),
      entry("streaming-layout", "Streaming overlay layout", GripVertical, "Streaming dock", "Selects up to 12 metric tiles across all accounts, orders them globally by drag or accessible move controls, and saves the versioned layout explicitly.", ["ADMIN"]),
      entry("streaming-preview", "Streaming draft preview", Eye, "Streaming dock", "Previews the unsaved tile order, provider badges, status states, and optional two-line custom footer.", ["ADMIN"]),
      entry("clipboard-fullscreen", "Open clipboard fullscreen", Maximize2, "Clipboard dock", "Expands private clipboard history into a full-screen workspace."),
      entry("clipboard-note", "Add clipboard note", Plus, "Clipboard dock", "Creates a private manual note in the Space-wide clipboard history."),
      entry("clipboard-clear", "Clear all clipboard items", Trash2, "Clipboard dock", "Permanently clears clipboard history for the authenticated account."),
      entry("clipboard-drag", "Drag clip", GripVertical, "Clipboard item", "Drags clipboard text to a compatible Space destination."),
      entry("clipboard-insert", "Insert clipboard item", Copy, "Clipboard item", "Inserts saved text into the active chat or CLI pane.", ["CONDITIONAL"]),
      entry("clipboard-delete", "Delete clip", Trash2, "Clipboard item", "Removes one clipboard history item from the private collection."),
      entry("default-provider", "Default provider", ServerCog, "Settings dock", "Selects the provider shared by newly configured agents and CLI defaults."),
      entry("telegram", "Telegram notifications", Bot, "Settings dock", "Connects a private Telegram bot for Codex task-completion notifications.", ["ADMIN", "CONDITIONAL"]),
      entry("telegram-refresh", "Refresh Telegram status", RefreshCw, "Telegram settings", "Reloads the secure connection, pairing, and delivery status."),
      entry("telegram-reconnect", "Reconnect Telegram bot", RotateCw, "Telegram settings", "Starts a protected token replacement or reconnect flow.", ["ADMIN"]),
      entry("telegram-test", "Send Telegram test message", Send, "Telegram settings", "Sends a test notification to the paired private chat.", ["ADMIN", "CONDITIONAL"]),
      entry("telegram-disconnect", "Disconnect Telegram", Unplug, "Telegram settings", "Disconnects the bot after an explicit confirmation.", ["ADMIN"]),
      entry("telegram-toggle", "Enable completion notifications", Bell, "Telegram settings", "Turns completion delivery on or off without deleting the pairing.", ["ADMIN", "CONDITIONAL"]),
      entry("voice", "Voice input", Mic, "Settings dock", "Configures browser microphone transcription for chat prompts."),
      entry("voice-refresh", "Refresh voice settings", RefreshCw, "Voice settings", "Reloads the available transcription providers and current voice configuration."),
      entry("cli-photo-limit", "CLI photo previews", Images, "Settings dock", "Sets how many transient uploaded-image previews are retained per CLI pane."),
      entry("agent-settings", "Agent settings", MessageSquare, "Settings dock", "Changes the selected chat pane model, reasoning configuration, and available tools."),
      entry("agent-tools", "Agent tools", Wrench, "Settings dock", "Enables or disables available tools for the selected chat agent."),
      entry("health-runtime", "Runtime health", ServerCog, "Health dock", "Shows runtime store, Temporal state, and worker readiness."),
      entry("health-worker", "Worker health", UserCheck, "Health dock", "Shows worker status, poller count, and task queue."),
      entry("health-storage", "Storage health", HardDrive, "Health dock", "Shows free application storage, root utilization, and dedicated-volume status."),
      entry("health-mcp", "MCP health", ShieldCheck, "Health dock", "Shows MCP gateway status, server count, tool count, and latest smoke result."),
      entry("health-requests", "Request health", Activity, "Health dock", "Shows request count, p95 latency, and current error count.")
    ]
  },
  {
    id: "memory-and-dashboards",
    title: "Memory and embedded links",
    summary: "Memory graph navigation, change review, maintenance visibility, and safely embedded personal links.",
    entries: [
      entry("memory-open", "Memory graph", Network, "Memory workspace", "Displays connected memory nodes and their relationships in the full workspace."),
      entry("memory-search", "Search memory", Search, "Memory workspace", "Searches visible memory by query and the selected taxonomy or scope filters."),
      entry("memory-filter", "Filter memory", ListFilter, "Memory workspace", "Narrows the graph and list views using the available memory filters."),
      entry("memory-list", "Memory list view", Database, "Memory workspace", "Switches from graph exploration to a compact list of memory nodes."),
      entry("memory-refresh", "Refresh memory workspace", RefreshCw, "Memory workspace", "Reloads graph data, issues, jobs, and change sets."),
      entry("memory-close", "Close memory workspace", X, "Memory workspace", "Returns from the full memory workspace to the active room."),
      entry("memory-edit", "Edit memory node", Pencil, "Memory node detail", "Stages an editable memory change for review rather than silently overwriting data."),
      entry("memory-archive", "Archive memory node", Archive, "Memory node detail", "Stages archival of an obsolete node through the protected change flow."),
      entry("memory-merge", "Merge memory nodes", GitMerge, "Memory node detail", "Stages consolidation of overlapping nodes while preserving provenance."),
      entry("memory-issue", "Memory issue", TriangleAlert, "Memory workspace", "Marks a contradiction, orphan, stale claim, or other detected memory issue.", ["INFORMATIONAL"]),
      entry("memory-changes", "Protected change set", ShieldAlert, "Memory workspace", "Opens pending, applied, or rejected changes for review and evidence."),
      entry("memory-change-back", "Previous memory item", ChevronLeft, "Memory workspace", "Moves to the previous node, issue, or change-set item."),
      entry("memory-change-next", "Next memory item", ChevronRight, "Memory workspace", "Moves to the next node, issue, or change-set item."),
      entry("memory-rollback", "Rollback memory change", RotateCcw, "Memory change detail", "Requests rollback of an applied memory change when rollback is available.", ["CONDITIONAL"]),
      entry("dashboard-refresh", "Refresh embedded link", RefreshCw, "Link dialog", "Reloads the currently embedded link."),
      entry("dashboard-external", "Open link externally", ExternalLink, "Link dialog", "Opens the current link in a protected separate browser tab."),
      entry("dashboard-close", "Close embedded link", X, "Link dialog", "Closes the embedded link and restores focus to the room view.")
    ]
  },
  {
    id: "responsive-and-customization",
    title: "Responsive layout and customization",
    summary: "How Space adapts toolbars and panes while preserving access to every action.",
    entries: [
      entry("toolbar-customization", "Toolbar customization", GripVertical, "Room, pane, and browser toolbars", "Drag actions to save a preferred order independently for each toolbar."),
      entry("toolbar-hide", "Hide toolbar action", EyeOff, "Toolbar context menu", "Right-click an eligible action and hide it from the primary toolbar."),
      entry("toolbar-show", "Show hidden toolbar action", Eye, "Toolbar action manager", "Restores a hidden action to its saved toolbar order."),
      entry("toolbar-overflow", "Overflow action manager", MoreHorizontal, "Responsive toolbars", "Keeps every action available when the viewport cannot display the complete toolbar."),
      entry("mobile-pane-switcher", "Mobile pane switcher", PanelTopOpen, "Mobile room view", "Switches the one visible mobile pane while preserving every other room pane."),
      entry("mobile-pane-focus", "Focus mobile pane", Maximize2, "Mobile pane controls", "Uses the full mobile viewport for the selected pane."),
      entry("mobile-pane-restore", "Restore mobile pane", Minimize2, "Mobile pane controls", "Returns from focused-pane mode to the mobile pane switcher."),
      entry("responsive-density", "Automatic pane density", Grid2X2, "Room board", "Adjusts minimum pane width and spacing for desktop, tablet, mobile, and high pane counts.", ["INFORMATIONAL"])
    ]
  },
  {
    id: "status-symbols",
    title: "Status and mode symbols",
    summary: "Icons that explain state but do not perform an action by themselves.",
    entries: [
      entry("status-loading", "Loading", Loader2, "Across Space", "Indicates that a request, session attachment, upload, or background refresh is in progress.", ["INFORMATIONAL"]),
      entry("status-success", "Success or ready", CheckCircle2, "Across Space", "Marks a completed action, healthy dependency, or verified result.", ["INFORMATIONAL"]),
      entry("status-warning", "Warning", TriangleAlert, "Across Space", "Marks degraded, gated, stale, or attention-required state without implying failure.", ["INFORMATIONAL"]),
      entry("status-error", "Error", CircleAlert, "Across Space", "Marks an action or dependency that failed and requires investigation.", ["INFORMATIONAL"]),
      entry("status-locked", "Locked or protected", Lock, "Permissions and tools", "Shows that a control is forced on, protected, or unavailable to the current role.", ["INFORMATIONAL"]),
      entry("status-selected", "Selected or current", Check, "Menus and pickers", "Marks the currently selected task, model, provider, tool, or option.", ["INFORMATIONAL"]),
      entry("mode-chat", "Chat pane symbol", MessageSquare, "Pane badge", "Identifies a native Codex chat pane.", ["INFORMATIONAL"]),
      entry("mode-cli", "CLI pane symbol", Terminal, "Pane badge", "Identifies a protected command-line or agent-runtime pane.", ["INFORMATIONAL"]),
      entry("mode-browser", "Browser pane symbol", Eye, "Pane badge", "Identifies a managed Chrome browser pane.", ["INFORMATIONAL"]),
      entry("mode-review", "Review pane symbol", GitCompare, "Pane badge", "Identifies a review-oriented workflow pane.", ["INFORMATIONAL"]),
      entry("mode-code", "Code pane symbol", Terminal, "Pane badge", "Identifies a code-oriented workflow pane.", ["INFORMATIONAL"]),
      entry("mode-swarm", "Swarm pane symbol", Users, "Pane badge", "Identifies a swarm-coordination workflow pane.", ["INFORMATIONAL"]),
      entry("mode-design", "Design pane symbol", Sparkles, "Pane badge", "Identifies a design-oriented workflow pane.", ["INFORMATIONAL"])
    ]
  }
];

export const helpEntries = helpSections.flatMap((section) => section.entries);
