import type { SystemHealthSnapshot } from "@space/contracts";

/** Demo-only telemetry. Live health always comes from the authenticated API. */
export function demoHealthSnapshot(
  at = new Date().toISOString(),
): SystemHealthSnapshot {
  return {
    sampledAt: at,
    coreCount: 8,
    uptimeSeconds: 86400,
    metrics: [
      {
        id: "cpu",
        label: "CPU",
        group: "cpu",
        unit: "PERCENT",
        value: 38,
        total: 100,
        detail: "Total server CPU utilization",
        sampledAt: at,
      },
      {
        id: "memory",
        label: "Memory",
        group: "memory",
        unit: "PERCENT",
        value: 47,
        total: 100,
        detail: "Server RAM in use, excluding available cache",
        sampledAt: at,
      },
      {
        id: "memory-used",
        label: "Memory used",
        group: "memory",
        unit: "BYTES",
        value: 8 * 1024 ** 3,
        total: 16 * 1024 ** 3,
        detail: "Used server RAM",
        sampledAt: at,
      },
      {
        id: "swap",
        label: "Swap",
        group: "swap",
        unit: "PERCENT",
        value: 3,
        total: 100,
        detail: "Server swap in use",
        sampledAt: at,
      },
      {
        id: "disk-app",
        label: "Space disk",
        group: "disk",
        unit: "PERCENT",
        value: 61,
        total: 100,
        detail: "/opt/spaceapp",
        sampledAt: at,
      },
      {
        id: "disk-root",
        label: "Root disk",
        group: "disk",
        unit: "PERCENT",
        value: 53,
        total: 100,
        detail: "/",
        sampledAt: at,
      },
      {
        id: "disk:vda:read",
        label: "vda read",
        group: "disk",
        unit: "BYTES_PER_SECOND",
        value: 4 * 1024 ** 2,
        detail: "Read throughput · vda",
        sampledAt: at,
      },
      {
        id: "disk:vda:write",
        label: "vda write",
        group: "disk",
        unit: "BYTES_PER_SECOND",
        value: 2 * 1024 ** 2,
        detail: "Write throughput · vda",
        sampledAt: at,
      },
      {
        id: "disk:vda:busy",
        label: "vda active",
        group: "disk",
        unit: "PERCENT",
        value: 13,
        detail: "Device busy time · vda",
        sampledAt: at,
      },
      {
        id: "network:eth0:rx",
        label: "eth0 receive",
        group: "network",
        unit: "BYTES_PER_SECOND",
        value: 1700000,
        detail: "eth0 · Default route",
        sampledAt: at,
      },
      {
        id: "network:eth0:tx",
        label: "eth0 send",
        group: "network",
        unit: "BYTES_PER_SECOND",
        value: 560000,
        detail: "eth0 · Default route",
        sampledAt: at,
      },
      {
        id: "network:eth0:usage",
        label: "eth0 utilization",
        group: "network",
        unit: "PERCENT",
        value: 12,
        total: 100,
        detail: "eth0 · Default route · 1000 Mbps full duplex",
        sampledAt: at,
      },
      {
        id: "request-errors",
        label: "API error rate",
        group: "requests",
        unit: "PERCENT",
        value: 0,
        detail: "HTTP 5xx · Last 5 min",
        sampledAt: at,
      },
      {
        id: "request-p95",
        label: "API p95",
        group: "requests",
        unit: "MILLISECONDS",
        value: 122,
        detail: "Response duration · Last 5 min",
        sampledAt: at,
      },
    ],
    requests: {
      windowSeconds: 300,
      requestCount: 240,
      errorCount: 0,
      errorRatePercent: 0,
      p95Ms: 122,
      sampledAt: at,
    },
    services: [
      "Space API",
      "Database",
      "Temporal & worker",
      "CLI host",
      "Browser host",
      "Storage readiness",
      "MCP gateway",
      "Active provider",
    ].map((label, index) => ({
      id: [
        "api",
        "database",
        "worker",
        "cli-host",
        "browser-host",
        "storage",
        "mcp",
        "provider",
      ][index]!,
      label,
      status: "healthy",
      detail: "Demo service readiness",
      checkedAt: at,
      values:
        label === "Temporal & worker"
          ? [
              { label: "Workflow pollers", value: "2" },
              { label: "Activity backlog", value: "0" },
            ]
          : [],
    })),
  };
}
