ALTER TABLE memory_embedding_smoke_checks
  DROP CONSTRAINT IF EXISTS memory_embedding_smoke_checks_code_check;

ALTER TABLE memory_embedding_smoke_checks
  ADD CONSTRAINT memory_embedding_smoke_checks_code_check
  CHECK (code IN (
    'EMBEDDING_SMOKE_DISABLED',
    'RUNTIME_STORE_NOT_POSTGRES',
    'PGVECTOR_UNAVAILABLE',
    'EMBEDDING_PROVIDER_MISSING',
    'EMBEDDING_PROVIDER_UNVERIFIED',
    'EMBEDDING_PROVIDER_UNSUPPORTED',
    'EMBEDDING_KEY_NAME_NOT_DEDICATED',
    'EMBEDDING_CREDENTIAL_MISSING',
    'EMBEDDING_KEY_FILE_UNREADABLE',
    'EMBEDDING_PROVIDER_CONFIG_INVALID',
    'EMBEDDING_PROVIDER_SMOKE_FAILED',
    'EMBEDDING_PROVIDER_RESPONSE_INVALID',
    'EMBEDDING_DIMENSIONS_MISMATCH',
    'EMBEDDING_SMOKE_OK'
  ));
