// Document-start script injected into managed Chrome pages via
// Page.addScriptToEvaluateOnNewDocument. It guards on the YouTube hostname so
// it is a no-op on every other site the managed browser visits.
//
// The technique mirrors what actively-maintained YouTube ad blockers use in
// 2026: prune the ad fields out of the innertube player JSON (playerAds,
// adPlacements, adSlots, adBreakHeartbeatParams) both on the initial global
// and on the /youtubei/v1/* fetch/XHR responses, hide the known ad containers
// with CSS, and fast-forward/skip any ad that still starts playing. Plain
// network-domain blocking no longer works because ads are served from the same
// googlevideo.com hosts as real video and are driven by the player JSON.
export function youTubeAdBlockScript(): string {
  return [
    "(function () {",
    "  'use strict';",
    "  var host = '';",
    "  try { host = location.hostname; } catch (e) { return; }",
    "  if (!/(^|\\.)(youtube\\.com|youtube-nocookie\\.com|youtubekids\\.com)$/.test(host)) return;",
    "",
    "  var AD_KEYS = ['playerAds', 'adPlacements', 'adSlots', 'adBreakHeartbeatParams'];",
    "",
    "  function prune(obj) {",
    "    if (!obj || typeof obj !== 'object') return obj;",
    "    for (var i = 0; i < AD_KEYS.length; i++) {",
    "      var key = AD_KEYS[i];",
    "      if (key in obj) { try { delete obj[key]; } catch (e) { try { obj[key] = []; } catch (e2) {} } }",
    "    }",
    "    try {",
    "      if (obj.auxiliaryUi && obj.auxiliaryUi.messageRenderers) {",
    "        delete obj.auxiliaryUi.messageRenderers.upsellDialogRenderer;",
    "      }",
    "    } catch (e) {}",
    "    return obj;",
    "  }",
    "",
    "  function prunePayload(json) {",
    "    if (!json || typeof json !== 'object') return json;",
    "    prune(json);",
    "    if (json.playerResponse) prune(json.playerResponse);",
    "    return json;",
    "  }",
    "",
    "  var INNERTUBE = /\\/youtubei\\/v1\\/(player|next|get_watch|reel_watch_sequence|search)/;",
    "",
    "  try {",
    "    var ipr;",
    "    Object.defineProperty(window, 'ytInitialPlayerResponse', {",
    "      configurable: true,",
    "      get: function () { return ipr; },",
    "      set: function (value) { ipr = prune(value); }",
    "    });",
    "  } catch (e) {}",
    "",
    "  try {",
    "    var originalFetch = window.fetch;",
    "    if (typeof originalFetch === 'function') {",
    "      window.fetch = function (input, init) {",
    "        var url = '';",
    "        try { url = typeof input === 'string' ? input : (input && input.url) || ''; } catch (e) {}",
    "        var result = originalFetch.apply(this, arguments);",
    "        if (!INNERTUBE.test(url)) return result;",
    "        return result.then(function (response) {",
    "          try {",
    "            var clone = response.clone();",
    "            return clone.text().then(function (text) {",
    "              try {",
    "                var json = prunePayload(JSON.parse(text));",
    "                return new Response(JSON.stringify(json), {",
    "                  status: response.status,",
    "                  statusText: response.statusText,",
    "                  headers: response.headers",
    "                });",
    "              } catch (e) { return response; }",
    "            }).catch(function () { return response; });",
    "          } catch (e) { return response; }",
    "        });",
    "      };",
    "    }",
    "  } catch (e) {}",
    "",
    "  try {",
    "    var XHR = window.XMLHttpRequest;",
    "    if (XHR && XHR.prototype) {",
    "      var originalOpen = XHR.prototype.open;",
    "      var originalSend = XHR.prototype.send;",
    "      XHR.prototype.open = function (method, url) {",
    "        try { this.__ytAdBlockUrl = typeof url === 'string' ? url : ''; } catch (e) {}",
    "        return originalOpen.apply(this, arguments);",
    "      };",
    "      XHR.prototype.send = function () {",
    "        var xhr = this;",
    "        var target = '';",
    "        try { target = xhr.__ytAdBlockUrl || ''; } catch (e) {}",
    "        if (INNERTUBE.test(target)) {",
    "          xhr.addEventListener('readystatechange', function () {",
    "            if (xhr.readyState !== 4) return;",
    "            try {",
    "              var json = prunePayload(JSON.parse(xhr.responseText));",
    "              var rewritten = JSON.stringify(json);",
    "              Object.defineProperty(xhr, 'responseText', { value: rewritten, configurable: true });",
    "              Object.defineProperty(xhr, 'response', { value: rewritten, configurable: true });",
    "            } catch (e) {}",
    "          });",
    "        }",
    "        return originalSend.apply(this, arguments);",
    "      };",
    "    }",
    "  } catch (e) {}",
    "",
    "  var AD_SELECTORS = [",
    "    '#masthead-ad', '#player-ads', 'ytd-ad-slot-renderer', 'ytd-display-ad-renderer',",
    "    'ytd-promoted-sparkles-web-renderer', 'ytd-in-feed-ad-layout-renderer',",
    "    '.ytp-ad-overlay-container', '.ytp-ad-text-overlay', 'ytd-statement-banner-renderer',",
    "    'ytd-player-legacy-desktop-watch-ads-renderer', 'ytd-ads-engagement-panel-content-renderer'",
    "  ].join(',');",
    "  function injectCss() {",
    "    try {",
    "      var style = document.createElement('style');",
    "      style.setAttribute('data-space-ad-block', '1');",
    "      style.textContent = AD_SELECTORS + '{display:none !important;}';",
    "      (document.head || document.documentElement).appendChild(style);",
    "    } catch (e) {}",
    "  }",
    "  if (document.head || document.documentElement) injectCss();",
    "  else document.addEventListener('DOMContentLoaded', injectCss, { once: true });",
    "",
    "  function skipVisibleAd() {",
    "    try {",
    "      var player = document.querySelector('.html5-video-player');",
    "      if (!player || !player.classList || !player.classList.contains('ad-showing')) return;",
    "      var skip = document.querySelector('.ytp-ad-skip-button, .ytp-skip-ad-button, .ytp-ad-skip-button-modern, button[class*=ytp-ad-skip]');",
    "      if (skip && skip.click) { skip.click(); return; }",
    "      var video = document.querySelector('video');",
    "      if (video && isFinite(video.duration) && video.duration > 0) {",
    "        try { video.muted = true; video.currentTime = video.duration; } catch (e) {}",
    "      }",
    "    } catch (e) {}",
    "  }",
    "  try { window.setInterval(skipVisibleAd, 300); } catch (e) {}",
    "})();"
  ].join("\n");
}

